name: Test Cases

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      - name: Install Poetry
        uses: snok/install-poetry@v1.3.4
        with:
          version: latest
      - name: Install dependencies JB lib
        working-directory: ./jb-lib
        run: poetry install --with test
      - name: Test JB lib
        working-directory: ./jb-lib
        run: poetry run pytest
      - name: Install dependencies channel
        working-directory: ./channel
        run: poetry install --with test
      - name: Test channel with pytest
        working-directory: ./channel
        run: poetry run pytest
      - name: Install dependencies language
        working-directory: ./language
        run: poetry install --with test
      - name: Test language with pytest
        working-directory: ./language
        run: poetry run pytest

